import type { Category, Product, Testimonial } from '@/types';

export const categories: Category[] = [
  {
    id: 'screens',
    name: 'Screens & Displays',
    icon: '📱',
    description: 'OLED, LCD replacements for all brands',
    count: 342,
  },
  {
    id: 'batteries',
    name: 'Batteries',
    icon: '🔋',
    description: 'High-capacity genuine replacements',
    count: 215,
  },
  {
    id: 'cameras',
    name: 'Camera Modules',
    icon: '📷',
    description: 'Front & rear cameras, lenses',
    count: 178,
  },
  {
    id: 'charging',
    name: 'Charging Ports',
    icon: '⚡',
    description: 'USB-C, Lightning connectors',
    count: 134,
  },
  {
    id: 'back-covers',
    name: 'Back Covers',
    icon: '🔲',
    description: 'Glass & plastic back panels',
    count: 290,
  },
  {
    id: 'speakers',
    name: 'Speakers & Audio',
    icon: '🔊',
    description: 'Earpieces, loudspeakers, mics',
    count: 156,
  },
  {
    id: 'buttons',
    name: 'Buttons & Flex',
    icon: '🔘',
    description: 'Power, volume, home buttons',
    count: 203,
  },
  {
    id: 'tools',
    name: 'Repair Tools',
    icon: '🔧',
    description: 'Professional repair tool kits',
    count: 89,
  },
];

export const products: Product[] = [
  {
    id: 'p1',
    name: 'iPhone 15 Pro OLED Screen Assembly',
    brand: 'Apple',
    model: 'iPhone 15 Pro',
    price: 89.99,
    originalPrice: 119.99,
    rating: 4.8,
    reviewCount: 234,
    image: 'https://images.unsplash.com/photo-1601784551446-20c9e07cdbdb?w=400&h=400&fit=crop',
    badge: 'sale',
    inStock: true,
    category: 'screens',
  },
  {
    id: 'p2',
    name: 'Samsung Galaxy S24 Battery 4000mAh',
    brand: 'Samsung',
    model: 'Galaxy S24',
    price: 24.99,
    originalPrice: 24.99,
    rating: 4.6,
    reviewCount: 187,
    image: 'https://images.unsplash.com/photo-1585338107529-13afc5f02586?w=400&h=400&fit=crop',
    badge: 'popular',
    inStock: true,
    category: 'batteries',
  },
  {
    id: 'p3',
    name: 'iPhone 14 Rear Camera Module',
    brand: 'Apple',
    model: 'iPhone 14',
    price: 54.99,
    originalPrice: 69.99,
    rating: 4.7,
    reviewCount: 98,
    image: 'https://images.unsplash.com/photo-1512054502232-10a0a035d672?w=400&h=400&fit=crop',
    badge: 'sale',
    inStock: true,
    category: 'cameras',
  },
  {
    id: 'p4',
    name: 'Google Pixel 8 USB-C Charging Port',
    brand: 'Google',
    model: 'Pixel 8',
    price: 18.99,
    originalPrice: 18.99,
    rating: 4.5,
    reviewCount: 63,
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=400&fit=crop',
    badge: 'new',
    inStock: true,
    category: 'charging',
  },
  {
    id: 'p5',
    name: 'Samsung S23 Ultra Back Glass Panel',
    brand: 'Samsung',
    model: 'Galaxy S23 Ultra',
    price: 34.99,
    originalPrice: 44.99,
    rating: 4.4,
    reviewCount: 142,
    image: 'https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?w=400&h=400&fit=crop',
    badge: 'sale',
    inStock: true,
    category: 'back-covers',
  },
  {
    id: 'p6',
    name: 'Professional Phone Repair Tool Kit',
    brand: 'PartsPro',
    model: 'Universal',
    price: 29.99,
    originalPrice: 39.99,
    rating: 4.9,
    reviewCount: 511,
    image: 'https://images.unsplash.com/photo-1504148455328-c376907d081c?w=400&h=400&fit=crop',
    badge: 'popular',
    inStock: true,
    category: 'tools',
  },
  {
    id: 'p7',
    name: 'iPhone 13 Battery 3227mAh',
    brand: 'Apple',
    model: 'iPhone 13',
    price: 19.99,
    originalPrice: 19.99,
    rating: 4.7,
    reviewCount: 329,
    image: 'https://images.unsplash.com/photo-1567581935884-3349723552ca?w=400&h=400&fit=crop',
    badge: 'popular',
    inStock: true,
    category: 'batteries',
  },
  {
    id: 'p8',
    name: 'OnePlus 12 AMOLED Display Assembly',
    brand: 'OnePlus',
    model: 'OnePlus 12',
    price: 74.99,
    originalPrice: 94.99,
    rating: 4.5,
    reviewCount: 47,
    image: 'https://images.unsplash.com/photo-1548421563-e0d5dc3f9ece?w=400&h=400&fit=crop',
    badge: 'new',
    inStock: true,
    category: 'screens',
  },
];

export const testimonials: Testimonial[] = [
  {
    id: 't1',
    name: 'Marcus Thompson',
    role: 'Independent Repair Technician',
    avatar: 'MT',
    rating: 5,
    text: 'PartsPro has been my go-to supplier for over 3 years. The quality is consistently excellent and shipping is always fast. My customers are always satisfied with the results.',
  },
  {
    id: 't2',
    name: 'Sarah Chen',
    role: 'Phone Repair Shop Owner',
    avatar: 'SC',
    rating: 5,
    text: 'The wholesale pricing is unbeatable and the parts are genuine quality. I\'ve tried other suppliers but always come back to PartsPro. The customer service team is also incredibly helpful.',
  },
  {
    id: 't3',
    name: 'James Rodriguez',
    role: 'DIY Repair Enthusiast',
    avatar: 'JR',
    rating: 4,
    text: 'Fixed my iPhone screen myself for the first time using a screen from PartsPro. The quality was great and the repair guides they provide made everything so easy. Will definitely order again.',
  },
];
